modLoader="javafml"
loaderVersion="[33,)"
license="MIT License"
#issueTrackerURL="https://github.com/MinecraftSpaceProgram/MSP/issues"

[[mods]]
modId="msp"
version="1.16.2-0.1.0"
displayName="Minecraft Space Program"
displayURL="https://MinecraftSpaceProgram.github.io"
logoFile="MSP_banner.png"
credits="KSP check them out they're awseome"
authors="viccol961 and Garfield1002"
description='''Build rockets and venture into space !'''

[[dependencies.msp]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.msp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"
